### ISSUE TITLE
Error with recent PR merge: Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by khalwat** [craftcms/rector#5] opened 2022-05-14 16:57 UTC
### Description

Using these `require-dev` dependencies for Craft 4: https://github.com/craftcms/cms/blob/develop/composer.json#L67

```json
  "require-dev": {
    "codeception/codeception": "^4.1.29",
    "codeception/module-asserts": "^1.3.1",
    "codeception/module-datafactory": "^1.1.0",
    "codeception/module-phpbrowser": "^1.0.2",
    "codeception/module-rest": "^1.4.2",
    "codeception/module-yii2": "^1.1.5"
}
```

or using these `require-dev` dependencies for Craft 3: https://github.com/craftcms/cms/blob/v3/composer.json#L61

```json
  "require-dev": {
    "codeception/codeception": "^4.0.0",
    "codeception/module-asserts": "^1.0.0",
    "codeception/module-datafactory": "^1.0.0",
    "codeception/module-phpbrowser": "^1.0.0",
    "codeception/module-rest": "^1.0.0",
    "codeception/module-yii2": "^1.0.0",
}
```

...and then adding `craftcms/rector`:
```json
    "craftcms/rector": "dev-main",
```

...results in:

***Your requirements could not be resolved to an installable set of packages.***

I believe it's a result of this PR: https://github.com/craftcms/rector/pull/4

...which bumps up the dependencies, resulting in a cascade:

```
plugindev-php_v3-1         | Your requirements could not be resolved to an installable set of packages.
plugindev-php_v3-1         | 
plugindev-php_v3-1         |   Problem 1
plugindev-php_v3-1         |     - codeception/module-datafactory 1.0.0 requires php >=5.6.0 <8.0 -> your php version (8.0.13) does not satisfy that requirement.
plugindev-php_v3-1         |     - codeception/codeception[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.x-dev, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8] require php >=5.6.0 <8.0 -> your php version (8.0.13) does not satisfy that requirement.
plugindev-php_v3-1         |     - symfony/console[v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, 4.0.x-dev, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.1.10, v4.1.11, v4.1.12, 4.1.x-dev, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.2.10, v4.2.11, v4.2.12, 4.2.x-dev, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.3.10, v4.3.11, 4.3.x-dev, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.0, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8] require php ^7.1.3 -> your php version (8.0.13) does not satisfy that requirement.
plugindev-php_v3-1         |     - symfony/console[v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1] require php ^7.2.9 -> your php version (8.0.13) does not satisfy that requirement.
plugindev-php_v3-1         |     - symfony/console[v5.0.0, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.1.0-BETA1, v5.1.0-RC1] require php ^7.2.5 -> your php version (8.0.13) does not satisfy that requirement.
plugindev-php_v3-1         |     - Root composer.json requires craftcms/rector dev-main -> satisfiable by craftcms/rector[dev-main].
plugindev-php_v3-1         |     - Root composer.json requires codeception/module-datafactory ^1.0.0 -> satisfiable by codeception/module-datafactory[1.0.0, 1.0.1, 1.1.0].
plugindev-php_v3-1         |     - codeception/module-datafactory[1.0.1, 1.1.0] require codeception/codeception ^4.0 -> satisfiable by codeception/codeception[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.x-dev, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.1.9, 4.1.11, 4.1.12, 4.1.13, 4.1.14, 4.1.15, 4.1.16, 4.1.17, 4.1.18, 4.1.19, 4.1.20, 4.1.21, 4.1.22, 4.1.23, 4.1.24, 4.1.25, 4.1.26, 4.1.27, 4.1.28, 4.1.29, 4.1.30, 4.1.31, 4.1.x-dev, 4.2.x-dev].
plugindev-php_v3-1         |     - codeception/codeception[4.1.9, 4.1.11, 4.1.12, 4.1.13, 4.1.14, 4.1.15, 4.1.16, 4.1.17, 4.1.18, 4.1.19, 4.1.20, 4.1.21, 4.1.22, 4.1.23, 4.1.24, 4.1.25, 4.1.26, 4.1.27, 4.1.28, 4.1.29, 4.1.30, 4.1.31, 4.1.x-dev, 4.2.x-dev] require symfony/console >=2.7 <6.0 -> satisfiable by symfony/console[v2.7.0-BETA1, v2.7.0-BETA2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.44, v2.7.45, v2.7.46, v2.7.47, v2.7.48, v2.7.49, v2.7.50, v2.7.51, 2.7.x-dev, v2.8.0-BETA1, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.49, v2.8.50, v2.8.52, 2.8.x-dev, v3.0.0-BETA1, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, 3.0.x-dev, v3.1.0-BETA1, v3.1.0-RC1, v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.1.10, 3.1.x-dev, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, 3.2.x-dev, v3.3.0-BETA1, v3.3.0-RC1, v3.3.0, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, 3.3.x-dev, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.40, v3.4.41, v3.4.42, v3.4.43, v3.4.44, v3.4.45, v3.4.46, v3.4.47, 3.4.x-dev, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, 4.0.x-dev, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.1.10, v4.1.11, v4.1.12, 4.1.x-dev, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.2.10, v4.2.11, v4.2.12, 4.2.x-dev, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.3.10, v4.3.11, 4.3.x-dev, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.0, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.20, v4.4.21, v4.4.22, v4.4.23, v4.4.24, v4.4.25, v4.4.26, v4.4.27, v4.4.29, v4.4.30, v4.4.33, v4.4.34, v4.4.36, v4.4.37, v4.4.38, v4.4.40, v4.4.41, 4.4.x-dev, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.0, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.0.10, v5.0.11, 5.0.x-dev, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.1.10, v5.1.11, 5.1.x-dev, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3, v5.2.0-RC1, v5.2.0-RC2, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.10, v5.2.11, v5.2.12, v5.2.14, 5.2.x-dev, v5.3.0-BETA1, v5.3.0-BETA2, v5.3.0-BETA3, v5.3.0-BETA4, v5.3.0-RC1, v5.3.0, v5.3.2, v5.3.4, v5.3.6, v5.3.7, v5.3.10, v5.3.11, v5.3.13, v5.3.14, v5.3.16, 5.3.x-dev, v5.4.0-BETA1, v5.4.0-RC1, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.5, v5.4.7, v5.4.8, 5.4.x-dev].
plugindev-php_v3-1         |     - You can only install one version of a package, so only one of these can be installed: symfony/console[v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.40, v2.3.41, v2.3.42, 2.3.x-dev, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.4.10, 2.4.x-dev, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.5.10, v2.5.11, v2.5.12, 2.5.x-dev, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.6.10, v2.6.11, v2.6.12, v2.6.13, 2.6.x-dev, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.44, v2.7.45, v2.7.46, v2.7.47, v2.7.48, v2.7.49, v2.7.50, v2.7.51, 2.7.x-dev, v2.8.0-BETA1, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.49, v2.8.50, v2.8.52, 2.8.x-dev, v3.0.0-BETA1, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, 3.0.x-dev, v3.1.0-BETA1, v3.1.0-RC1, v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.1.10, 3.1.x-dev, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.0, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, 3.2.x-dev, v3.3.0-BETA1, v3.3.0-RC1, v3.3.0, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, 3.3.x-dev, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.40, v3.4.41, v3.4.42, v3.4.43, v3.4.44, v3.4.45, v3.4.46, v3.4.47, 3.4.x-dev, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, 4.0.x-dev, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.1.10, v4.1.11, v4.1.12, 4.1.x-dev, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.2.10, v4.2.11, v4.2.12, 4.2.x-dev, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.3.10, v4.3.11, 4.3.x-dev, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.0, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.20, v4.4.21, v4.4.22, v4.4.23, v4.4.24, v4.4.25, v4.4.26, v4.4.27, v4.4.29, v4.4.30, v4.4.33, v4.4.34, v4.4.36, v4.4.37, v4.4.38, v4.4.40, v4.4.41, 4.4.x-dev, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.0, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.0.10, v5.0.11, 5.0.x-dev, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.1.10, v5.1.11, 5.1.x-dev, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3, v5.2.0-RC1, v5.2.0-RC2, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.10, v5.2.11, v5.2.12, v5.2.14, 5.2.x-dev, v5.3.0-BETA1, v5.3.0-BETA2, v5.3.0-BETA3, v5.3.0-BETA4, v5.3.0-RC1, v5.3.0, v5.3.2, v5.3.4, v5.3.6, v5.3.7, v5.3.10, v5.3.11, v5.3.13, v5.3.14, v5.3.16, 5.3.x-dev, v5.4.0-BETA1, v5.4.0-RC1, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.5, v5.4.7, v5.4.8, 5.4.x-dev, v6.0.0-BETA1, v6.0.0-RC1, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.5, v6.0.7, v6.0.8, 6.0.x-dev, v6.1.0-BETA1, v6.1.0-BETA2, 6.1.x-dev].
plugindev-php_v3-1         |     - Conclusion: install symfony/console v6.0.8 (conflict analysis result)
```

Removing the dependency of:
```json
    "craftcms/rector": "dev-main",
```
...fixes the issue, and allows Composer to install everything (but then we don't have Rector installed)

### Steps to reproduce

1. See above

### Additional info

- Craft version: Craft CMS `^3.7.26` & Craft CMS `^4.0.0`
- PHP version: PHP 7.2.5 & 8.0.13
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by TomasVotruba** [comment] 2022-05-14 17:01
Thanks for repoting :+1: 

That's because craftcms/rector uses Rector in dev-main:
https://github.com/craftcms/rector/blob/990d30d4657cee599b7bcb013b921c4da6faae6c/composer.json#L6

You can require it in your package, or wait for my fix :+1:

**Comment by khalwat** [comment] 2022-05-14 17:03
Do you think `craftcms/rector` should be using a tagged release in its `composer.json` @TomasVotruba ?

**Comment by TomasVotruba** [comment] 2022-05-14 17:04
Let's try: https://github.com/craftcms/rector/pull/6 
Looking at your report again, it might be not enough though. Could you verify?


> Do you think craftcms/rector should be using a tagged release in its composer.json @TomasVotruba ?

Definitelly on `require` section, so people don't have issue you've reported.

**Comment by TomasVotruba** [comment] 2022-05-14 17:05
Btw, your PHP verison does not match the requirements:

```bash
- codeception/module-datafactory 1.0.0 requires php >=5.6.0 <8.0 -> your php version (8.0.13) does not satisfy that requirement.
```
 

You'll need to upgrade codeception to PHP 8.0+ version first.

**Comment by khalwat** [comment] 2022-05-14 17:07
It's PHP 8.0.13 already... **your php version (8.0.13)**

**Comment by TomasVotruba** [comment] 2022-05-14 17:08
Could you share exact copy-paste steps to reproduce in bash on PHP 8.0? I'll try locally

**Comment by TomasVotruba** [comment] 2022-05-14 17:09
Yeah, the PHP version is ok. But the codeceptoin is old:


- codeception/ .. 1.0.0 requires php >=5.6.0 <8.0 = **5.6 and PHP 7.**, PHP 8 is too new

**Comment by khalwat** [comment] 2022-05-14 17:10
I'm using the Codeception versions that Craft CMS has pinned (linked in the initial post). So I'm using what P&T is using for Craft CMS currently.

All of this worked without issue until the recent PR, so I'm thinking that's the issue.

As for running it locally, absolutely! Just fire up this project:

https://github.com/nystudio107/plugindev

**Comment by TomasVotruba** [comment] 2022-05-14 17:16
> I'm using the Codeception versions that Craft CMS has pinned (linked in the initial post) in their actual composer.json files in craftcms/cms. So I'm using what P&T is using for Craft CMS currently.

It's also possible the patch version of codeception can support PHP 7 or 8, depending on exact patch version of another dependency :) I've seen some similar mess in such project lacking united monorepo versioning.

> As for running it locally, absolutely! Just fire up this project:

Thanks. It seems it requires Docker, but I don't use it:
I'll need something simple as  "git clone/composer require", so we can test it in CI here to confirm it works in the long run.

**Comment by khalwat** [comment] 2022-05-14 17:21
> Thanks. It seems it requires Docker, but I don't use it:

It's an easy install if you want to test it: https://docs.docker.com/desktop/

> I'll need something simple as "git clone/composer require", so we can test it in CI here to confirm it works in the long run.

It should be as easy as having a composer.json that looks like this:

https://github.com/nystudio107/plugindev/blob/develop/cms_v4/composer.json

...and then doing a `composer install`

Or you could use the Craft CMS `composer.json`: https://github.com/craftcms/cms/blob/develop/composer.json

...and add Rector to `require-dev`:

```json
    "craftcms/rector": "dev-main",
```

**Comment by TomasVotruba** [comment] 2022-05-14 17:23
I'm not using Docker on purpose :) 

So, something like:

```bash
git cloe git@github.com:craftcms/cms.git
cd cms
composer require craftcms/rector
```

**Comment by TomasVotruba** [comment] 2022-05-14 17:25
I see it. The private accessor from Symplify :+1:

**Comment by TomasVotruba** [comment] 2022-05-14 20:04
Closed by https://github.com/craftcms/rector/pull/7

**Closed by TomasVotruba** 2022-05-14 20:04 UTC
Labels: bug
